// Copyright 2009 the Sputnik authors.  All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/**
* @name: S8.8_D1.1;
* @section: 8.8;
* @assertion: Arguments list may have up to 512 elements;
* @description: Call function with 512 arguments;
*/

__mFunc=Function("return arguments.length;");

if (__mFunc('8','8','The','List','Type','The','internal','List','type','is','not','a','language','data','type','1','It','is','defined','by','this','specification','purely','for','expository','purposes','1','An','implementation','of','ECMAScript','must','behave','as','if','it','produced','and','operated','upon','List','values','in','the','manner','described','here','1','However','1','a','value','of','the','List','type','is','used','only','as','an','intermediate','result','of','expression','evaluation','and','cannot','be','stored','as','the','value','of','a','variable','or','property','1','The','List','type','is','used','to','explain','the','evaluation','of','argument','lists','(see','11','2','4)','in','new','expressions','and','in','function','calls','1','Values','of','the','List','type','are','simply','ordered','sequences','of','values','1','These','sequences','may','be','of','any','length','1','8','8','The','List','Type',
'8','8','The','List','Type','The','internal','List','type','is','not','a','language','data','type','1','It','is','defined','by','this','specification','purely','for','expository','purposes','1','An','implementation','of','ECMAScript','must','behave','as','if','it','produced','and','operated','upon','List','values','in','the','manner','described','here','1','However','1','a','value','of','the','List','type','is','used','only','as','an','intermediate','result','of','expression','evaluation','and','cannot','be','stored','as','the','value','of','a','variable','or','property','1','The','List','type','is','used','to','explain','the','evaluation','of','argument','lists','(see','11','2','4)','in','new','expressions','and','in','function','calls','1','Values','of','the','List','type','are','simply','ordered','sequences','of','values','1','These','sequences','may','be','of','any','length','1','8','8','The','List','Type',
'8','8','The','List','Type','The','internal','List','type','is','not','a','language','data','type','1','It','is','defined','by','this','specification','purely','for','expository','purposes','1','An','implementation','of','ECMAScript','must','behave','as','if','it','produced','and','operated','upon','List','values','in','the','manner','described','here','1','However','1','a','value','of','the','List','type','is','used','only','as','an','intermediate','result','of','expression','evaluation','and','cannot','be','stored','as','the','value','of','a','variable','or','property','1','The','List','type','is','used','to','explain','the','evaluation','of','argument','lists','(see','11','2','4)','in','new','expressions','and','in','function','calls','1','Values','of','the','List','type','are','simply','ordered','sequences','of','values','1','These','sequences','may','be','of','any','length','1','8','8','The','List','Type',
'8','8','The','List','Type','The','internal','List','type','is','not','a','language','data','type','1','It','is','defined','by','this','specification','purely','for','expository','purposes','1','An','implementation','of','ECMAScript','must','behave','as','if','it','produced','and','operated','upon','List','values','in','the','manner','described','here','1','However','1','a','value','of','the','List','type','is','used','only','as','an','intermediate','result','of','expression','evaluation','and','cannot','be','stored','as','the','value','of','a','variable','or','property','1','The','List','type','is','used','to','explain','the','evaluation','of','argument','lists','(see','11','2','4)','in','new','expressions','and','in','function','calls','1','Values','of','the','List','type','are','simply','ordered','sequences','of','values','1','These','sequences','may','be','of','any','length','1','8','8','The','List','Type') !== 512) {
  $ERROR('#1: Arguments list may have up to 512 elements');
}
