#pragma once
#include "./class/array_header.h"
#include "./class/boolean_header.h"
#include "./class/function_header.h"
#include "./class/native_header.h"
#include "./class/number_header.h"
#include "./class/object_header.h"
#include "./class/string_header.h"
#include "./class/undefined_header.h"
